# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll
title: Puget Sound Repeater Roundabout
description: The weekend of November 19th, get to know our local repeaters!

author: Quentin K7DRQ (quentincaudron@gmail.com)
author_email: "quentincaudron@gmail.com"

navbar-links:
  Home: "/"
  Rules: "/rules"
  Repeaters: "/repeaters"
  Map: "/map"
  Radio Files: "/files"
  Logging: "/logging"
  Chat: "https://discord.com/invite/mqkD4fTjrn"

avatar: "/assets/images/logo.png"

gtag: "G-N7S873N5DC"

site-css:
  - assets/css/style.css
  - assets/css/spectrum.css
